spring.application.name=auth-service
#spring.datasource.url=jdbc:postgresql://localhost:5432/eams
#spring.datasource.username=tarangpatil09
#spring.datasource.password=mysql69
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
